updated pipline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,11 +1,9 @@
-# Define global variables and options for Maven commands
 variables:
   MAVEN_OPTS: >-
     -Dhttps.protocols=TLSv1.2
     -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
     -Dorg.slf4j.simpleLogger.showDateTime=true
     -Djava.awt.headless=true
-
   MAVEN_CLI_OPTS: >-
     --batch-mode
     --errors
@@ -15,10 +13,8 @@ variables:
     -DinstallAtEnd=true
     -DdeployAtEnd=true
 
-# Using Maven with OpenJDK 17 for the CI/CD pipeline
 image: maven:3-openjdk-17
 
-# Cache Maven dependencies between builds
 cache:
   paths:
     - .m2/repository
@@ -27,22 +23,20 @@ stages:
   - verify
   - deploy
 
-# Test stage - Verify the build
 verify:
   stage: verify
   script:
     - 'mvn $MAVEN_CLI_OPTS verify'
 
-# Deploy stage - Deploy to GitLab Maven repository on main and feature branches
 deploy:
   stage: deploy
   script:
     - |
       if [ ! -f ci_settings.xml ]; then
-        echo "CI settings missing! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."
-        exit 1  # Ensure the script exits if the file is missing
+        echo "CI settings file missing! Please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."
+        exit 1
       fi
     - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml'
   only:
     - main
-    - /^feature\/.*$/  # This will allow deploys on all feature branches
+    - /^feature\/.*$/
