fix: test fixing

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -38,6 +38,11 @@ verify:
 deploy:
   stage: deploy
   script:
+    - |
+      if [ ! -f ci_settings.xml ]; then
+        echo "CI settings file missing! Please see https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for instructions."
+        exit 1
+      fi
     - 'mvn $MAVEN_CLI_OPTS deploy --settings ci_settings.xml -DskipTests'
   only:
     - main
